# site properties and page defaults
title: IMEC Lab
subtitle: Intelligent Mobile and Embedded Computing Lab
description: At IMEC, we work at the intersection between systems, embedded AI, and data. We develop resource-efficient and real-time systems that can embed intelligent perception, reasoning, and understanding into common infrastructure and everyday objects found all around us and utilize these systems in efficient ways to enable useful services and improve our overall quality of life. Our work spans a number of domains, including mobile and embedded systems, cyber-physical systems, edge computing, signal processing, machine learning, wearables, robotics, health, intelligent built environments, etc.
header: images/aerial960__FitMaxWzk3MCw2NTBd.jpg
footer: images/tech.jpg
logo-text: false
header-dark: false

# site social media and other links
links:
  email: stephen.xia@northwestern.edu
  orcid: 0000-0001-5713-8885
  google-scholar: b6PNcXQAAAAJ&view_op=list_works&sortby=pubdate
  github: donkerdude?tab=repositories
  #twitter: donkerdude
  #youtube: donkerdude

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
